# Verdadeiros
print(bool(True))
print(bool(1))
print(bool(123))
print(bool(1.1))
print(bool(-1))
print(bool(1j))
print(bool("oi"))
print(bool([1, 2, 3]))
print(bool((1, 2, 3)))
print(bool({1, 2, 3}))

print("-" * 30)
# Falsos
print(bool(False))
print(bool(0))
print(bool(0.0))
print(bool(0j))
print(bool(""))
print(bool([]))
print(bool(()))
print(bool({}))
print(bool(None))
